name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-comand: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.iputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-comand: yarn install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.iputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-firefox:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-comand: yarn install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.iputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
